# This module contains all the necessary code and functions for reading in data
# files generated by Labview. The files are usually in .txt format. There are
# currently two types of files included in this; IV curves data and Hall magnetic
# field sweep data.

import numpy as np
import os


