# This is the setup file for a skeleton project as suggested by 
# 'Learn Python the Hard Way' in its skeleton directory page.

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

config = {
    'description' : 'This project handles data generated by the Oxford Maglab 200 system.',
    'author': 'Neil Campbell',
    'url': 'www.github.com/9ngribbenc1',
    'download_url': 'www.github.com/9ngribbenc1/downloads',
    'author_email': '9ngribbenc1@gmail.com',
    'version': '0.1',
    'install_requires': ['nose'],
    'packages': ['maglabdata'],
    'scripts': [],
    'name': 'maglabdata'
}

setup(**config)


